# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
