# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 11:56
from __future__ import unicode_literals

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_page_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image2',
            field=models.ImageField(default=None, null=True, upload_to=book.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='page',
            name='image1',
            field=models.ImageField(default=None, null=True, upload_to=book.models.path_and_rename),
        ),
    ]
