# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 14:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20160702_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 7, 2, 14, 42, 52, 277099, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
